### ISSUE TITLE
When call getDialogs() function, Response error code 200 is occurred.

### ISSUE THREAD

**Issue by xspire** [ConnectyCube/connectycube-flutter-samples#83]
**Specify the sample to which the issue belongs (use [x]):**
[x ] Chat sample
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
When call getDialogs() function, Response error code 200 is occurred as the below.

**Steps to Reproduce:**
1. call getDialogs() function

**Logs:**
```
When call getDialogs() function, Response error code 200 is occurred as log below.

flutter: CB-SDK: : getDialogs after 2021-05-10T23:27:49.000
flutter: CB-SDK: : =========================================================
flutter: === REQUEST ==== 508a4b7c-6d52-46c8-a54c-10a3e48355ec ===
flutter: REQUEST
flutter:   GET https://api.connectycube.com/chat/Dialog?created_at[gt]=1620656869.0&sort_asc=created_at
flutter: HEADERS
flutter:   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.4-dev.1, CB-Token: FB920FD65F0731DDBCE5953CA6BB8E68FBB7}
flutter: BODY

I/flutter (29847): CB-SDK: : getDialogs after 2021-05-10T23:27:49.000
I/flutter (29847): CB-SDK: : =========================================================
I/flutter (29847): === REQUEST ==== 5ab105f6-948f-4eae-95d9-2e2687889513 ===
I/flutter (29847): REQUEST
I/flutter (29847): GET https://api.connectycube.com/chat/Dialog?created_at[gt]=1620656869.0&sort_asc=created_at
I/flutter (29847): HEADERS
I/flutter (29847): {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.4-dev.1, CB-Token: 85DBD2935CF7A3A2C95E16107B08DAD09838}
I/flutter (29847): BODY
I/flutter (29847):
I/flutter (29847):
[log] ---Xmpp Sending:---
[log] 
[log] ---Xmpp Receiving:---
[log] 
[log] ---Xmpp Sending:---
[log] 
[log] ---Xmpp Receiving:---
[log] 
I/flutter (29847): CB-SDK: : *********************************************************
I/flutter (29847): *** RESPONSE *** 200 *** 5ab105f6-948f-4eae-95d9-2e2687889513 ***
I/flutter (29847): HEADERS
I/flutter (29847): {cb-token-expirationdate: 2021-05-11 18:29:18 UTC, connection: keep-alive, date: Tue, 11 May 2021 16:29:18 GMT, content-length: 1120, strict-transport-security: max-age=15768000; includeSubDomains, content-type: application/json; charset=utf-8, server: nginx/1.16.1}
I/flutter (29847): BODY
I/flutter (29847): {"total_entries":2,"skip":0,"limit":100,"items":[{"_id":"xxxxxxxx","user_id":12341234,"created_at":"2021-05-07T15:07:05Z","updated_at":"2021-05-07T15:07:41Z","name":"xxxx","description":"xxxx","type":2,"occupants_ids":[12341234,23452345],"occupants_count":2,"xmpp_room_jid":"xxxxx","is_e2ee":false,"admins_ids":[],"last_message":"{msgtype: ...
```

Respected result : 

No  item is in the returned list in the current state of registered chat room.

**Comment by TatankaConCube** [comment]
200 is the `OK` [code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses). Or you mean another problem?

**Comment by xspire** [comment]
@TatankaConCube 
Ok, i understand for return code.

A more messages for calling getDialog function is added above. Check it.

I call getDialogs with getDialogs with after last time limit parameter what have 2021-05-10T23:27:49.000.
But the returned list have chat room info for 2021-05-07T15:07:05Z ...

    Map<String, dynamic> additionalParams = {
      created_at[gt]: 1620656869, 
      "sort_asc" : "created_at"
    };

In my connectycube admin page, Only two chat room is registered what created at 21.5.7, 21.5.10.
But returned list has the two chat room info.

**Comment by TatankaConCube** [comment]
looks like the server-side issue, notified them, will back to you later with updates

**Comment by DaveLomber** [comment]
@xspire this should be fixed, please check

**Comment by xspire** [comment]
@DaveLomber
It's not solved.
It still returns all dialogs info list.

CB-SDK: : getDialogs after 2021-05-10T23:27:49.000
I/flutter (24024): CB-SDK: : =========================================================
I/flutter (24024): === REQUEST ==== 28f4f3ed-8090-471a-a583-01c8af6e7d5e ===
I/flutter (24024): REQUEST
I/flutter (24024):   GET https://api.connectycube.com/chat/Dialog?created_at[gt]=1620656869.0&sort_asc=created_at 
I/flutter (24024): HEADERS
I/flutter (24024):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.4-dev.1, CB-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}

**Comment by TatankaConCube** [comment]
in your request parameter `created_at[gt]` set as `double` `1620656869.0`, try use `int` for it

**Comment by DaveLomber** [comment]
Please check now

**Comment by xspire** [comment]
Thank you. It is fixed with below code.
int timetocheck =  (nowt.millisecondsSinceEpoch / 1000).toInt();
